# Generated by Django 4.0.4 on 2023-06-05 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='postal_code',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
    ]
