# Generated by Django 4.0.4 on 2023-06-05 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_postal_code_order_phone_remove_order_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
    ]
